<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Lección 5 Matrices | AprendeR: Parte I</title>
  <meta name="description" content="Apuntes AprendeR bookdown::gitbook.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Lección 5 Matrices | AprendeR: Parte I" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apuntes AprendeR bookdown::gitbook." />
  <meta name="github-repo" content="RicUIB/AprendeR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lección 5 Matrices | AprendeR: Parte I" />
  
  <meta name="twitter:description" content="Apuntes AprendeR bookdown::gitbook." />
  

<meta name="author" content="The AprendeR team">


<meta name="date" content="2019-02-14">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="chap-vect.html">
<link rel="next" href="chap-df.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">AprendeR: Parte I</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentación</a></li>
<li class="chapter" data-level="1" data-path="chap-0.html"><a href="chap-0.html"><i class="fa fa-check"></i><b>1</b> Logística de <code>R</code></a><ul>
<li class="chapter" data-level="1.1" data-path="chap-0.html"><a href="chap-0.html#como-instalar-r-y-rstudio"><i class="fa fa-check"></i><b>1.1</b> Cómo instalar <code>R</code> y <em>Rstudio</em></a></li>
<li class="chapter" data-level="1.2" data-path="chap-0.html"><a href="chap-0.html#sec:guardar"><i class="fa fa-check"></i><b>1.2</b> Cómo guardar el trabajo realizado</a></li>
<li class="chapter" data-level="1.3" data-path="chap-0.html"><a href="chap-0.html#sec:guiones"><i class="fa fa-check"></i><b>1.3</b> Cómo trabajar con guiones y otros ficheros</a></li>
<li class="chapter" data-level="1.4" data-path="chap-0.html"><a href="chap-0.html#sec:help"><i class="fa fa-check"></i><b>1.4</b> Cómo obtener ayuda</a></li>
<li class="chapter" data-level="1.5" data-path="chap-0.html"><a href="chap-0.html#sec:paquetes"><i class="fa fa-check"></i><b>1.5</b> Cómo instalar y cargar paquetes</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chap-calc.html"><a href="chap-calc.html"><i class="fa fa-check"></i><b>2</b> La calculadora</a><ul>
<li class="chapter" data-level="2.1" data-path="chap-calc.html"><a href="chap-calc.html#numeros-reales-operaciones-y-funciones-basicas"><i class="fa fa-check"></i><b>2.1</b> Números reales: operaciones y funciones básicas</a></li>
<li class="chapter" data-level="2.2" data-path="chap-calc.html"><a href="chap-calc.html#cifras-significativas-y-redondeos"><i class="fa fa-check"></i><b>2.2</b> Cifras significativas y redondeos</a></li>
<li class="chapter" data-level="2.3" data-path="chap-calc.html"><a href="chap-calc.html#definicion-de-variables"><i class="fa fa-check"></i><b>2.3</b> Definición de variables</a></li>
<li class="chapter" data-level="2.4" data-path="chap-calc.html"><a href="chap-calc.html#definicion-de-funciones"><i class="fa fa-check"></i><b>2.4</b> Definición de funciones</a></li>
<li class="chapter" data-level="2.5" data-path="chap-calc.html"><a href="chap-calc.html#numeros-complejos-opcional"><i class="fa fa-check"></i><b>2.5</b> Números complejos (opcional)</a></li>
<li class="chapter" data-level="2.6" data-path="chap-calc.html"><a href="chap-calc.html#guia-rapida"><i class="fa fa-check"></i><b>2.6</b> Guía rápida</a></li>
<li class="chapter" data-level="2.7" data-path="chap-calc.html"><a href="chap-calc.html#ejercicio"><i class="fa fa-check"></i><b>2.7</b> Ejercicio</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-lm.html"><a href="chap-lm.html"><i class="fa fa-check"></i><b>3</b> Un aperitivo: Introducción a la regresión lineal</a><ul>
<li class="chapter" data-level="3.1" data-path="chap-lm.html"><a href="chap-lm.html#calculo-de-rectas-de-regresion"><i class="fa fa-check"></i><b>3.1</b> Cálculo de rectas de regresión</a></li>
<li class="chapter" data-level="3.2" data-path="chap-lm.html"><a href="chap-lm.html#rectas-de-regresion-y-transformaciones-logaritmicas"><i class="fa fa-check"></i><b>3.2</b> Rectas de regresión y transformaciones logarítmicas</a></li>
<li class="chapter" data-level="3.3" data-path="chap-lm.html"><a href="chap-lm.html#guia-rapida-1"><i class="fa fa-check"></i><b>3.3</b> Guía rápida</a></li>
<li class="chapter" data-level="3.4" data-path="chap-lm.html"><a href="chap-lm.html#ejercicio-1"><i class="fa fa-check"></i><b>3.4</b> Ejercicio</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap-vect.html"><a href="chap-vect.html"><i class="fa fa-check"></i><b>4</b> Vectores y otros tipos de listas</a><ul>
<li class="chapter" data-level="4.1" data-path="chap-vect.html"><a href="chap-vect.html#construccion-de-vectores"><i class="fa fa-check"></i><b>4.1</b> Construcción de vectores</a></li>
<li class="chapter" data-level="4.2" data-path="chap-vect.html"><a href="chap-vect.html#operaciones-con-vectores"><i class="fa fa-check"></i><b>4.2</b> Operaciones con vectores</a></li>
<li class="chapter" data-level="4.3" data-path="chap-vect.html"><a href="chap-vect.html#entradas-y-trozos-de-vectores"><i class="fa fa-check"></i><b>4.3</b> Entradas y trozos de vectores</a></li>
<li class="chapter" data-level="4.4" data-path="chap-vect.html"><a href="chap-vect.html#subsec:factor"><i class="fa fa-check"></i><b>4.4</b> Factores</a></li>
<li class="chapter" data-level="4.5" data-path="chap-vect.html"><a href="chap-vect.html#sec:lists"><i class="fa fa-check"></i><b>4.5</b> Listas heterogéneas</a></li>
<li class="chapter" data-level="4.6" data-path="chap-vect.html"><a href="chap-vect.html#guia-rapida-de-funciones"><i class="fa fa-check"></i><b>4.6</b> Guía rápida de funciones</a></li>
<li class="chapter" data-level="4.7" data-path="chap-vect.html"><a href="chap-vect.html#ejercicio-2"><i class="fa fa-check"></i><b>4.7</b> Ejercicio</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap-matrix.html"><a href="chap-matrix.html"><i class="fa fa-check"></i><b>5</b> Matrices</a><ul>
<li class="chapter" data-level="5.1" data-path="chap-matrix.html"><a href="chap-matrix.html#construccion-de-matrices"><i class="fa fa-check"></i><b>5.1</b> Construcción de matrices</a></li>
<li class="chapter" data-level="5.2" data-path="chap-matrix.html"><a href="chap-matrix.html#acceso-a-entradas-y-submatrices"><i class="fa fa-check"></i><b>5.2</b> Acceso a entradas y submatrices</a></li>
<li class="chapter" data-level="5.3" data-path="chap-matrix.html"><a href="chap-matrix.html#algunas-funciones-para-matrices"><i class="fa fa-check"></i><b>5.3</b> Algunas funciones para matrices</a></li>
<li class="chapter" data-level="5.4" data-path="chap-matrix.html"><a href="chap-matrix.html#calculo-matricial-opcional"><i class="fa fa-check"></i><b>5.4</b> Cálculo matricial (opcional)</a></li>
<li class="chapter" data-level="5.5" data-path="chap-matrix.html"><a href="chap-matrix.html#valores-y-vectores-propios-opcional"><i class="fa fa-check"></i><b>5.5</b> Valores y vectores propios (opcional)</a></li>
<li class="chapter" data-level="5.6" data-path="chap-matrix.html"><a href="chap-matrix.html#matrices-complejas-opcional"><i class="fa fa-check"></i><b>5.6</b> Matrices complejas (opcional)</a></li>
<li class="chapter" data-level="5.7" data-path="chap-matrix.html"><a href="chap-matrix.html#guia-rapida-de-funciones-1"><i class="fa fa-check"></i><b>5.7</b> Guía rápida de funciones</a></li>
<li class="chapter" data-level="5.8" data-path="chap-matrix.html"><a href="chap-matrix.html#ejercicio-opcional"><i class="fa fa-check"></i><b>5.8</b> Ejercicio (opcional)</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap-df.html"><a href="chap-df.html"><i class="fa fa-check"></i><b>6</b> <em>Data frames</em></a><ul>
<li class="chapter" data-level="6.1" data-path="chap-df.html"><a href="chap-df.html#estructura-de-un-data-frame"><i class="fa fa-check"></i><b>6.1</b> Estructura de un <em>data frame</em></a></li>
<li class="chapter" data-level="6.2" data-path="chap-df.html"><a href="chap-df.html#como-importar-y-exportar-data-frames"><i class="fa fa-check"></i><b>6.2</b> Cómo importar y exportar <em>data frames</em></a></li>
<li class="chapter" data-level="6.3" data-path="chap-df.html"><a href="chap-df.html#como-crear-data-frames"><i class="fa fa-check"></i><b>6.3</b> Cómo crear <em>data frames</em></a></li>
<li class="chapter" data-level="6.4" data-path="chap-df.html"><a href="chap-df.html#sec:moddf"><i class="fa fa-check"></i><b>6.4</b> Cómo modificar un <em>data frame</em></a></li>
<li class="chapter" data-level="6.5" data-path="chap-df.html"><a href="chap-df.html#sec:dfaf"><i class="fa fa-check"></i><b>6.5</b> Cómo añadir filas y columnas a un <em>data frame</em></a></li>
<li class="chapter" data-level="6.6" data-path="chap-df.html"><a href="chap-df.html#como-seleccionar-trozos-de-un-data-frame"><i class="fa fa-check"></i><b>6.6</b> Cómo seleccionar trozos de un <em>data frame</em></a></li>
<li class="chapter" data-level="6.7" data-path="chap-df.html"><a href="chap-df.html#como-aplicar-una-funcion-a-las-variables-de-un-data-frame"><i class="fa fa-check"></i><b>6.7</b> Cómo aplicar una función a las variables de un <em>data frame</em></a></li>
<li class="chapter" data-level="6.8" data-path="chap-df.html"><a href="chap-df.html#sub:attach"><i class="fa fa-check"></i><b>6.8</b> Cómo añadir las variables de un <em>data frame</em> al entorno global</a></li>
<li class="chapter" data-level="6.9" data-path="chap-df.html"><a href="chap-df.html#big-data-frames-con-data.table-opcional."><i class="fa fa-check"></i><b>6.9</b> &lt;&lt;<em>Big data</em>&gt;&gt; <em>frames</em> con <code>data.table</code> (opcional).</a></li>
<li class="chapter" data-level="6.10" data-path="chap-df.html"><a href="chap-df.html#guia-rapida-de-funciones-2"><i class="fa fa-check"></i><b>6.10</b> Guía rápida de funciones</a></li>
<li class="chapter" data-level="6.11" data-path="chap-df.html"><a href="chap-df.html#ejercicio-3"><i class="fa fa-check"></i><b>6.11</b> Ejercicio</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap-plot.html"><a href="chap-plot.html"><i class="fa fa-check"></i><b>7</b> Gráficos I</a><ul>
<li class="chapter" data-level="7.1" data-path="chap-plot.html"><a href="chap-plot.html#la-funcion-plot"><i class="fa fa-check"></i><b>7.1</b> La función <code>plot</code></a></li>
<li class="chapter" data-level="7.2" data-path="chap-plot.html"><a href="chap-plot.html#parametros-de-plot"><i class="fa fa-check"></i><b>7.2</b> Parámetros de <code>plot</code></a></li>
<li class="chapter" data-level="7.3" data-path="chap-plot.html"><a href="chap-plot.html#como-anadir-elementos-a-un-grafico"><i class="fa fa-check"></i><b>7.3</b> Cómo añadir elementos a un gráfico</a></li>
<li class="chapter" data-level="7.4" data-path="chap-plot.html"><a href="chap-plot.html#guia-rapida-2"><i class="fa fa-check"></i><b>7.4</b> Guía rápida</a><ul>
<li class="chapter" data-level="7.4.1" data-path="chap-plot.html"><a href="chap-plot.html#ejercicio-4"><i class="fa fa-check"></i><b>7.4.1</b> Ejercicio</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap-edqual.html"><a href="chap-edqual.html"><i class="fa fa-check"></i><b>8</b> Descripción de datos cualitativos</a><ul>
<li class="chapter" data-level="8.1" data-path="chap-edqual.html"><a href="chap-edqual.html#frecuencias"><i class="fa fa-check"></i><b>8.1</b> Frecuencias</a></li>
<li class="chapter" data-level="8.2" data-path="chap-edqual.html"><a href="chap-edqual.html#tablas-unidimensionales-de-frecuencias"><i class="fa fa-check"></i><b>8.2</b> Tablas unidimensionales de frecuencias</a></li>
<li class="chapter" data-level="8.3" data-path="chap-edqual.html"><a href="chap-edqual.html#tablas-bidimensionales-de-frecuencias"><i class="fa fa-check"></i><b>8.3</b> Tablas bidimensionales de frecuencias</a></li>
<li class="chapter" data-level="8.4" data-path="chap-edqual.html"><a href="chap-edqual.html#tablas-multidimensionales-de-frecuencias"><i class="fa fa-check"></i><b>8.4</b> Tablas multidimensionales de frecuencias</a></li>
<li class="chapter" data-level="8.5" data-path="chap-edqual.html"><a href="chap-edqual.html#tablas-a-partir-de-dta-frames-de-de-variables-cualitativas"><i class="fa fa-check"></i><b>8.5</b> Tablas a partir de <em>dta frames</em> de de variables cualitativas</a></li>
<li class="chapter" data-level="8.6" data-path="chap-edqual.html"><a href="chap-edqual.html#diagramas-de-barras"><i class="fa fa-check"></i><b>8.6</b> Diagramas de barras</a></li>
<li class="chapter" data-level="8.7" data-path="chap-edqual.html"><a href="chap-edqual.html#otros-graficos-para-datos-cualitativos"><i class="fa fa-check"></i><b>8.7</b> Otros gráficos para datos cualitativos</a><ul>
<li class="chapter" data-level="8.7.1" data-path="chap-edqual.html"><a href="chap-edqual.html#sec:exqual"><i class="fa fa-check"></i><b>8.7.1</b> Un ejemplo completo</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="chap-edqual.html"><a href="chap-edqual.html#guia-rapida-de-funciones-3"><i class="fa fa-check"></i><b>8.8</b> Guía rápida de funciones</a></li>
<li class="chapter" data-level="8.9" data-path="chap-edqual.html"><a href="chap-edqual.html#ejercicio-5"><i class="fa fa-check"></i><b>8.9</b> Ejercicio</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap-ord.html"><a href="chap-ord.html"><i class="fa fa-check"></i><b>9</b> Descripción de datos ordinales</a><ul>
<li class="chapter" data-level="9.1" data-path="chap-ord.html"><a href="chap-ord.html#frecuencias-para-datos-ordinales"><i class="fa fa-check"></i><b>9.1</b> Frecuencias para datos ordinales</a></li>
<li class="chapter" data-level="9.2" data-path="chap-ord.html"><a href="chap-ord.html#descripcion-de-datos-ordinales-con-r"><i class="fa fa-check"></i><b>9.2</b> Descripción de datos ordinales con <code>R</code></a></li>
<li class="chapter" data-level="9.3" data-path="chap-ord.html"><a href="chap-ord.html#guia-rapida-de-funciones-4"><i class="fa fa-check"></i><b>9.3</b> Guía rápida de funciones</a></li>
<li class="chapter" data-level="9.4" data-path="chap-ord.html"><a href="chap-ord.html#ejercicio-6"><i class="fa fa-check"></i><b>9.4</b> Ejercicio</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/RicUIB/AprendeR2.1" target="blank">Publicado con  bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">AprendeR: Parte I</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap:matrix" class="section level1">
<h1><span class="header-section-number">Lección 5</span> Matrices</h1>
<p>Una <code>matriz de orden</code> <span class="math inline">\(n\times m\)</span> es una tabla rectangular de números (o, en algunas situaciones específicas, algún otro tipo de datos: valores lógicos, etiquetas…) formada por <span class="math inline">\(n\)</span> filas y <span class="math inline">\(m\)</span> columnas. Una matriz es <code>cuadrada</code> cuando tiene el mismo número de filas que de columnas, es decir, cuando <span class="math inline">\(n=m\)</span>; en este caso, decimos que la matriz es de <code>orden</code> <span class="math inline">\(n\)</span>. En matemáticas, es costumbre escribir las matrices rodeadas por paréntesis para marcar con claridad sus límites. Por ejemplo,</p>
<p><span class="math display">\[
A = \left(\begin{matrix}
2 &amp; 1 &amp; -3\\ -4 &amp; 3 &amp; \sqrt{3}\end{matrix}
\right)
\]</span></p>
<p>es una matriz <span class="math inline">\(2\times 3\)</span>.</p>
<div id="construccion-de-matrices" class="section level2">
<h2><span class="header-section-number">5.1</span> Construcción de matrices</h2>
<p>Disponemos de dos maneras básicas de definir una matriz en <code>R</code>. En primer lugar, la instrucción <code>matrix(vector , nrow=n, byrow=valor_lógico)</code> define una matriz de <span class="math inline">\(n\)</span> filas (<em>rows</em>) formada por las entradas del <code>vector</code> . Si se entra <code>byrow=TRUE</code>, la matriz se construye por filas, mientras que con <code>byrow=FALSE</code> se construye por columnas; este último es el valor por defecto, por lo que no hace falta especificarlo. En vez de emplear <code>nrow</code>, se puede indicar el número de columnas con <code>ncol</code>. Veamos algunos ejemplos:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, <span class="dt">nrow=</span><span class="dv">2</span>)</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    3    5
## [2,]    2    4    6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, <span class="dt">nrow=</span><span class="dv">3</span>)</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    4
## [2,]    2    5
## [3,]    3    6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    2    3
## [2,]    4    5    6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, <span class="dt">nrow=</span><span class="dv">3</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    2
## [2,]    3    4
## [3,]    5    6</code></pre>
<p>Observad cómo muestra <code>R</code> las matrices: indica las filas con <code>[i,]</code>, donde <span class="math inline">\(i\)</span> es el índice de la fila, y las columnas con <code>[,j]</code>, donde <span class="math inline">\(j\)</span> es el índice de la columna.</p>
<p>Para construir una matriz de <span class="math inline">\(n\)</span> filas o <span class="math inline">\(n\)</span> columnas, es conveniente que la longitud del vector al que se aplica <code>matrix</code> sea múltiplo de <span class="math inline">\(n\)</span>. Si no es así, <code>R</code> rellena la última fila o columna con entradas del principio del vector y emite un mensaje de advertencia.</p>
<pre><code>&gt; matrix(1:6, nrow=4) #6 no es múltiplo de 4
     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    1
[4,]    4    2
Warning message:
In matrix(1:6, nrow = 4) :
  data length [6] is not a sub-multiple or multiple of the number
  of rows [4]</code></pre>
<p>En particular, se puede definir una matriz constante aplicando la función <code>matrix</code> a un número. En este caso, se han de usar los parámetros <code>nrow</code> y <code>ncol</code> para especificar el orden de la matriz.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">matrix</span>(<span class="dv">1</span>, <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">ncol=</span><span class="dv">3</span>)   <span class="co">#Matriz constante 1 de orden 2x3</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    1    1
## [2,]    1    1    1</code></pre>
<p>Otra posible manera de definir matrices es combinando filas o columnas. La instrucción <code>rbind(vector1, vector2, ....)</code> construye la matriz de filas <em>vector1</em>, <em>vector2</em>,… (que han de tener la misma longitud) en este orden. Si en lugar de <code>rbind</code> se usa <code>cbind</code>, se obtiene la matriz cuyas columnas son los vectores a los que se aplica.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rbind</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">2</span>),<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">6</span>),<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">0</span>))</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    0    2
## [2,]    2    3    6
## [3,]    1    2    0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">2</span>),<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">6</span>),<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">0</span>))</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    2    1
## [2,]    0    3    2
## [3,]    2    6    0</code></pre>
<p>Con las funciones <code>cbind</code> o <code>rbind</code> también podemos añadir columnas, o filas, a una matriz; en concreto, si <span class="math inline">\(A\)</span> es una matriz de orden <span class="math inline">\(n\times m\)</span> y <span class="math inline">\(v\)</span> es un vector de longitud <span class="math inline">\(n\)</span>, la instrucción <code>cbind(A, v)</code> define la matriz de orden <span class="math inline">\(n\times(m+1)\)</span> que tiene como primeras <span class="math inline">\(m\)</span> columnas las de <span class="math inline">\(A\)</span> y como columna <span class="math inline">\(m+1\)</span> el vector <span class="math inline">\(v\)</span>; de manera similar, <code>cbind(v, A)</code> define la matriz de orden <span class="math inline">\(n\times(m+1)\)</span> que tiene como primera columna el vector <span class="math inline">\(v\)</span> y después las columnas de <span class="math inline">\(A\)</span>. Con <code>cbind</code> también podemos concatenar por columnas dos matrices con el mismo número de filas.</p>
<p>La instrucción <code>rbind</code> es similar a <code>cbind</code>, pero actúa por filas en vez de por columnas: permite añadir filas arriba o abajo de una matriz ya existente, y, en general, concatenar por filas dos matrices con el mismo número de columnas.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="dt">nrow=</span><span class="dv">2</span>)
A</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    3
## [2,]    2    4</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="dv">7</span>,<span class="dv">8</span>),<span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">6</span>),A)</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    7    5    1    3
## [2,]    8    6    2    4</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cbind</span>(A,A)</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    3    1    3
## [2,]    2    4    2    4</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rbind</span>(A,<span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">12</span>))</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    3
## [2,]    2    4
## [3,]   10   12</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rbind</span>(A,A)</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    3
## [2,]    2    4
## [3,]    1    3
## [4,]    2    4</code></pre>
<!--
Comentado en la version original .tex
%
%Hay otra manera de construir matrices que a veces resulta útil, empleando la instrucción
%
%`outer(`\textit{vector1}`,`\textit{vector2}`, FUN=`\textit{función}`)`.
%
%Esta instrucción construye la matriz donde cada entrada $(i, j)$ es el resultado de aplicar la `función`  al par formado por la entrada $i$-ésima del `vector1`  y la entrada $j$-ésima del `vector2` . 
%Si la función es un signo de operación, se ha de entrar entre comillas.
%```
%> vec1=c(2, 5)
%> vec2=c(1, 3, 1)
%> outer(vec1, vec2, FUN="+") 
%     [,1] [,2] [,3]
%[1,]    3    5    3
%[2,]    6    8    6
%> outer(vec1, vec2, FUN="*")
%     [,1] [,2] [,3]
%[1,]    2    6    2
%[2,]    5   15    5
%> f=function(x, y){sqrt(x^2+y^2)}
%> outer(vec1, vec2, FUN=f)
%         [,1]     [,2]     [,3]
%[1,] 2.236068 3.605551 2.236068
%[2,] 5.099020 5.830952 5.099020
%```
%
-->
<p>Como pasaba con los vectores, todas las entradas de una matriz en <code>R</code> han de ser del mismo tipo de datos, y si una matriz contiene datos de diferentes tipos, automáticamente los convierte a un tipo que pueda ser común a todos ellos.</p>
<p>Si los vectores que concatenamos con <code>rbind</code> o <code>cbind</code> tienen nombres, las filas o columnas correspondientes de la matriz los heredan.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x=<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>)
y=<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="op">-</span><span class="dv">1</span>)
<span class="kw">rbind</span>(x,y)</code></pre></div>
<pre><code>##   [,1] [,2] [,3]
## x    1    2    3
## y    0    1   -1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cbind</span>(x,y)</code></pre></div>
<pre><code>##      x  y
## [1,] 1  0
## [2,] 2  1
## [3,] 3 -1</code></pre>
<p>Se puede también poner nombres a las filas y las columnas de una matriz con la instrucción</p>
<p><code>dimnames(``matriz</code> <code>)=list(``vector de nombres de filas</code> <code>,``vector de nombres de columnas</code> <code>)</code>.</p>
<p>Si las filas o las columnas no han de tener nombres, se declara su vector de nombres como <code>NULL</code> en esta <code>list</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>,<span class="dt">nrow=</span><span class="dv">3</span>)
A</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    4
## [2,]    2    5
## [3,]    3    6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dimnames</span>(A)=<span class="kw">list</span>(<span class="kw">c</span>(<span class="st">&quot;X1&quot;</span>,<span class="st">&quot;X2&quot;</span>,<span class="st">&quot;X3&quot;</span>),<span class="kw">c</span>(<span class="st">&quot;Y1&quot;</span>,<span class="st">&quot;Y2&quot;</span>))
A</code></pre></div>
<pre><code>##    Y1 Y2
## X1  1  4
## X2  2  5
## X3  3  6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dimnames</span>(A)=<span class="kw">list</span>(<span class="ot">NULL</span>,<span class="kw">c</span>(<span class="st">&quot;Palma&quot;</span>,<span class="st">&quot;Barcelona&quot;</span>))
A</code></pre></div>
<pre><code>##      Palma Barcelona
## [1,]     1         4
## [2,]     2         5
## [3,]     3         6</code></pre>
<p>Los nombres de las filas y columnas de una matriz pueden servir para hacer más clara la información contenida en la misma.</p>
</div>
<div id="acceso-a-entradas-y-submatrices" class="section level2">
<h2><span class="header-section-number">5.2</span> Acceso a entradas y submatrices</h2>

<p>La <code>entrada $(i, j)$</code> de una matriz es el elemento situado en su fila <span class="math inline">\(i\)</span> y su columna <span class="math inline">\(j\)</span>. Por ejemplo, las entradas <span class="math inline">\((1,2)\)</span> y <span class="math inline">\((2,1)\)</span> de la matriz <span class="math display">\[
A = \left(\begin{matrix}
2 &amp; 1 &amp; -3\\ -4 &amp; 3 &amp; \sqrt{3}\end{matrix}
\right)
\]</span> son, respectivamente, <span class="math inline">\(1\)</span> y <span class="math inline">\(-4\)</span>.</p>
<p>El acceso a las entradas de una matriz se realiza como en los vectores, sólo que ahora en las matrices podemos especificar la fila y la columna:</p>
<ul>
<li><p><code>M[i, j]</code> indica la entrada <span class="math inline">\((i, j)\)</span> de la matriz <code>M</code>.</p></li>
<li><p><code>M[i, ]</code> indica la fila <span class="math inline">\(i\)</span>-ésima de <code>M</code>.</p></li>
<li><p><code>M[ ,j]</code> indica la columna <span class="math inline">\(j\)</span>-ésima de <code>M</code>.</p></li>
</ul>
<p>En los dos últimos casos, el resultado es un vector. Si queremos que el resultado sea una matriz de una sola fila o de una sola columna, respectivamente, tenemos que añadir el parámetro <code>drop=FALSE</code> dentro de los corchetes.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">2</span>,<span class="dv">9</span>,<span class="dv">8</span>,<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">5</span>), <span class="dt">nrow=</span><span class="dv">3</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
M</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    3    5    2
## [2,]    3    6    2    9
## [3,]    8    4    2    5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M[<span class="dv">2</span>,<span class="dv">4</span>]  <span class="co">#Entrada (2,4)</span></code></pre></div>
<pre><code>## [1] 9</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M[<span class="dv">3</span>,<span class="dv">1</span>]  <span class="co">#Entrada (3,1)</span></code></pre></div>
<pre><code>## [1] 8</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M[<span class="dv">1</span>, ]  <span class="co">#Fila 1</span></code></pre></div>
<pre><code>## [1] 1 3 5 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M[<span class="dv">1</span>, , drop=<span class="ot">FALSE</span>] <span class="co">#ATENCIÓN: fijaos en las dos comas</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    3    5    2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M[ ,<span class="dv">3</span>]  <span class="co">#Columna 3</span></code></pre></div>
<pre><code>## [1] 5 2 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M[ ,<span class="dv">3</span>, drop=<span class="ot">FALSE</span>]</code></pre></div>
<pre><code>##      [,1]
## [1,]    5
## [2,]    2
## [3,]    2</code></pre>
<p>Estas construcciones sirven también para definir submatrices, y no sólo entradas, filas o columnas. Naturalmente, para indicar más de una fila o más de una columna tenemos que usar vectores de índices.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M[<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>),<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)] <span class="co">#Submatriz de filas 1, 2 y columnas 1, 3</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    5
## [2,]    3    2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M[<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>), ] <span class="co">#Submatriz de filas 1, 3 y todas las columnas</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    3    5    2
## [2,]    8    4    2    5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M[ ,<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>)] <span class="co">#Submatriz de columnas 2, 3, 4 y todas las filas</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    3    5    2
## [2,]    6    2    9
## [3,]    4    2    5</code></pre>
<p>Si las filas o las columnas de una matriz tienen nombres, se pueden usar para especificar trozos de la misma.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">9</span>,<span class="dt">nrow=</span><span class="dv">3</span>)
<span class="kw">dimnames</span>(A)=<span class="kw">list</span>(<span class="kw">c</span>(<span class="st">&quot;X1&quot;</span>,<span class="st">&quot;X2&quot;</span>,<span class="st">&quot;X3&quot;</span>),<span class="kw">c</span>(<span class="st">&quot;Y1&quot;</span>,<span class="st">&quot;Y2&quot;</span>,<span class="st">&quot;Y3&quot;</span>))
A</code></pre></div>
<pre><code>##    Y1 Y2 Y3
## X1  1  4  7
## X2  2  5  8
## X3  3  6  9</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A[<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>),<span class="dv">2</span>]</code></pre></div>
<pre><code>## X1 X3 
##  4  6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A[<span class="kw">c</span>(<span class="st">&quot;X1&quot;</span>,<span class="st">&quot;X3&quot;</span>),<span class="st">&quot;Y2&quot;</span>]</code></pre></div>
<pre><code>## X1 X3 
##  4  6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A[<span class="kw">c</span>(<span class="st">&quot;X1&quot;</span>,<span class="st">&quot;X3&quot;</span>),<span class="kw">c</span>(<span class="st">&quot;Y1&quot;</span>,<span class="st">&quot;Y2&quot;</span>)]</code></pre></div>
<pre><code>##    Y1 Y2
## X1  1  4
## X3  3  6</code></pre>
<p>La diagonal principal de una matriz cuadrada (la que va de la esquina superior izquierda a la esquina inferior derecha) se obtiene con la función <code>diag</code>. Si la matriz no es cuadrada, <code>diag</code> produce el vector de entradas <span class="math inline">\((1, 1), (2, 2), \ldots\)</span> hasta que se para en la última fila o la última columna.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">9</span>, <span class="dt">nrow=</span><span class="dv">3</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
A </code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    2    3
## [2,]    4    5    6
## [3,]    7    8    9</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">diag</span>(A)</code></pre></div>
<pre><code>## [1] 1 5 9</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">B=<span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
B</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5]
## [1,]    1    2    3    4    5
## [2,]    6    7    8    9   10</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">diag</span>(B)</code></pre></div>
<pre><code>## [1] 1 7</code></pre>
</div>
<div id="algunas-funciones-para-matrices" class="section level2">
<h2><span class="header-section-number">5.3</span> Algunas funciones para matrices</h2>
<p>Las <code>dimensiones</code> de una matriz, es decir, sus números de filas y de columnas, se obtienen con las funciones <code>nrow</code> y <code>ncol</code>, respectivamente. Si queremos un vector formado por las dos dimensiones, podemos emplear la función <code>dim</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">1</span>,<span class="dv">6</span>,<span class="dv">4</span>), <span class="dt">byrow=</span><span class="ot">TRUE</span>, <span class="dt">nrow=</span><span class="dv">2</span>)
X</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6]
## [1,]    1    2    4    3    5    1
## [2,]    4    6    7    1    6    4</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">nrow</span>(X)</code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ncol</span>(X)</code></pre></div>
<pre><code>## [1] 6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(X)</code></pre></div>
<pre><code>## [1] 2 6</code></pre>
<p>La mayoría de las funciones numéricas para vectores se pueden aplicar a matrices. Por ejemplo, podemos<br />
usar las funciones <code>sum</code>, <code>prod</code> o <code>mean</code> para obtener la suma, el producto o la media, respectivamente, de todas las entradas de una matriz.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">3</span>,<span class="op">-</span><span class="dv">1</span>,<span class="dv">3</span>), <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
A</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    2    1
## [2,]    3   -1    3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(A)</code></pre></div>
<pre><code>## [1] 9</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(A)</code></pre></div>
<pre><code>## [1] 1.5</code></pre>
<p>En estadística a veces es necesario calcular la suma o la media por filas o por columnas de una matriz. Esto se puede llevar a cabo con las instrucciones siguientes:</p>
<ul>
<li><code>colSums</code> produce un vector con las sumas de las columnas.</li>
<li><code>rowSums</code> produce un vector con las sumas de las filas.</li>
<li><code>colMeans</code> produce un vector con las medias de las columnas.</li>
<li><code>rowMeans</code> produce un vector con las medias de las filas.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">rbind</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">2</span>),<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">3</span>,<span class="dv">1</span>),<span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>))
A</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    2    3    2
## [2,]    2    5    3    1
## [3,]    4    1    2    4</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">colSums</span>(A)  <span class="co">#Sumas de columnas</span></code></pre></div>
<pre><code>## [1] 7 8 8 7</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rowSums</span>(A)  <span class="co">#Sumas de filas</span></code></pre></div>
<pre><code>## [1]  8 11 11</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">colMeans</span>(A)  <span class="co">#Medias de columnas</span></code></pre></div>
<pre><code>## [1] 2.333333 2.666667 2.666667 2.333333</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rowMeans</span>(A)  <span class="co">#Medias de filas</span></code></pre></div>
<pre><code>## [1] 2.00 2.75 2.75</code></pre>
<p>Si queremos aplicar otras funciones a las filas o las columnas de una matriz, podemos emplear la función <code>apply</code>. Su estructura básica es</p>
<p><code>apply(A, MARGIN=\ldots, FUN=``función</code> <code>)</code>,</p>
<p>donde <code>A</code> es una matriz, la <code>función</code> es la que queremos aplicar, y el valor de <code>MARGIN</code> ha de ser 1 si la queremos aplicar por filas, 2 si la queremos aplicar por columnas, o <code>c(1, 2)</code> si la queremos aplicar entrada a entrada; como pasaba con los vectores, en muchas ocasiones podemos aplicar una función a todas las entradas de una matriz entrando la matriz en su argumento, pero a veces es necesario usar <code>apply</code> con <code>MARGIN=c(1,2)</code>.</p>
<p>Por ejemplo, para calcular la <code>norma euclídea</code> de las filas de la matriz <span class="math inline">\(A\)</span> anterior (la raíz cuadrada de la suma de los cuadrados de sus entradas), para ordenar cada una de sus columnas, y para calcular la matriz de raíces cuadradas de las entradas de <span class="math inline">\(A\)</span>, haríamos lo siguiente:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">f=<span class="cf">function</span>(x){<span class="kw">sqrt</span>(<span class="kw">sum</span>(x<span class="op">^</span><span class="dv">2</span>))}
<span class="kw">apply</span>(A, <span class="dt">MARGIN=</span><span class="dv">1</span>, <span class="dt">FUN=</span>f)  <span class="co">#Normas euclídeas de filas</span></code></pre></div>
<pre><code>## [1] 4.242641 6.244998 6.082763</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A_ord=<span class="kw">apply</span>(A, <span class="dt">MARGIN=</span><span class="dv">2</span>, <span class="dt">FUN=</span>sort)  <span class="co">#Matriz con cada columna de A ordenada</span>
A_ord</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    1    2    1
## [2,]    2    2    3    2
## [3,]    4    5    3    4</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sqrt</span>(A)   <span class="co">#Matriz de raíces cuadradas</span></code></pre></div>
<pre><code>##          [,1]     [,2]     [,3]     [,4]
## [1,] 1.000000 1.414214 1.732051 1.414214
## [2,] 1.414214 2.236068 1.732051 1.000000
## [3,] 2.000000 1.000000 1.414214 2.000000</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">apply</span>(A, <span class="dt">MARGIN=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="dt">FUN=</span>sqrt)  <span class="co">#La anterior, usando apply</span></code></pre></div>
<pre><code>##          [,1]     [,2]     [,3]     [,4]
## [1,] 1.000000 1.414214 1.732051 1.414214
## [2,] 1.414214 2.236068 1.732051 1.000000
## [3,] 2.000000 1.000000 1.414214 2.000000</code></pre>
</div>
<div id="calculo-matricial-opcional" class="section level2">
<h2><span class="header-section-number">5.4</span> Cálculo matricial (opcional)</h2>
<p>Las operaciones algebraicas usuales con matrices numéricas se indican de la manera siguiente:<a href="#fn23" class="footnoteRef" id="fnref23"><sup>23</sup></a></p>
<ul>
<li><p>La traspuesta se obtiene con la función <code>t</code>.</p></li>
<li><p>La suma de matrices se indica con el signo usual <code>+</code>.</p></li>
<li><p>El producto de un escalar por una matriz se indica con el signo usual <code>*</code>.</p></li>
<li><p>El producto de matrices se indica con <code>%*%</code>.</p></li>
</ul>
<p><strong>¡Atención!</strong> Si &lt;<multiplicáis>&gt; dos matrices con el signo <code>*</code>, no obtenéis el producto de las dos matrices, sino la matriz que tiene en cada entrada <span class="math inline">\((i, j)\)</span> el producto de las entradas <span class="math inline">\((i, j)\)</span> de cada una de las dos matrices. Esto a veces es útil, pero no es el producto de matrices. De manera similar, si <span class="math inline">\(M\)</span> es una matriz y entráis <code>M^n</code>, el resultado no es la potencia <span class="math inline">\(n\)</span>-ésima de <span class="math inline">\(M\)</span>, sino la matriz que tiene en cada entrada la potencia <span class="math inline">\(n\)</span>-ésima de la entrada correspondiente de <span class="math inline">\(M\)</span>. De nuevo, esto a veces es útil, pero muy pocas veces coincide con la potencia <span class="math inline">\(n\)</span>-ésima de <span class="math inline">\(M\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">3</span>), <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
A</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    2
## [2,]    1    3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">B=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">2</span>), <span class="dt">nrow=</span><span class="dv">3</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
B</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   -2    4
## [2,]    3    1
## [3,]    0    2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">C=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
C</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    0    1
## [2,]    2    1    0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t</span>(B) <span class="co">#Traspuesta</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]   -2    3    0
## [2,]    4    1    2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t</span>(B)<span class="op">+</span>C <span class="co">#Suma</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]   -1    3    1
## [2,]    6    2    2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">5</span><span class="op">*</span>A <span class="co">#Producto por escalar</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    5   10
## [2,]    5   15</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">C<span class="op">%*%</span>B <span class="co">#Producto</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   -2    6
## [2,]   -1    9</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(C<span class="op">%*%</span>B)<span class="op">%*%</span>A <span class="co">#Producto </span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    4   14
## [2,]    8   25</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A<span class="op">^</span><span class="dv">2</span> <span class="co">#Esto no es elevar al cuadrado</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    4
## [2,]    1    9</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A<span class="op">%*%</span>A  <span class="co">#Esto sí</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    3    8
## [2,]    4   11</code></pre>
<p>Al multiplicar matrices por vectores, <code>R</code> trata por defecto estos últimos como vectores columna, pero si en alguna situación concreta la manera natural de entender un vector es como vector fila, lo hace sin ningún reparo. Veamos algunos ejemplos:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">rbind</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>),<span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">4</span>))
A</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    2
## [2,]    3    4</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">v=<span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">6</span>)</code></pre></div>
<ul>
<li>El producto <span class="math display">\[
\left(\begin{array}{cc}
1 &amp; 2 \\ 3 &amp; 4\end{array}
\right)\cdot \left(\begin{array}{c}
5\\ 6\end{array}
\right)
\]</span> se obtiene mediante</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A<span class="op">%*%</span>v</code></pre></div>
<pre><code>##      [,1]
## [1,]   17
## [2,]   39</code></pre>
<ul>
<li>El producto <span class="math display">\[
\left(\begin{array}{cc}
5 &amp; 6\end{array}\right)\cdot\left(\begin{array}{cc}
1 &amp; 2 \\ 3 &amp; 4\end{array}
\right)
\]</span> se obtiene mediante</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">v<span class="op">%*%</span>A</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   23   34</code></pre>
<ul>
<li>El producto <span class="math display">\[
\left(\begin{array}{cc}
5 &amp; 6\end{array}\right)\cdot \left(\begin{array}{c}
5\\ 6\end{array}
\right)
\]</span> se obtiene mediante</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">v<span class="op">%*%</span>v</code></pre></div>
<pre><code>##      [,1]
## [1,]   61</code></pre>
<ul>
<li>El producto <span class="math display">\[
\left(\begin{array}{c}
5\\ 6\end{array}
\right)\cdot
\left(\begin{array}{cc}
5 &amp; 6\end{array}\right) \]</span> se obtiene mediante</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">v<span class="op">%*%</span><span class="kw">t</span>(v)</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   25   30
## [2,]   30   36</code></pre>
<p>La versión básica de <code>R</code> no lleva ninguna función para calcular potencias de matrices, y hay que cargar algún paquete adecuado para disponer de ella.<a href="#fn24" class="footnoteRef" id="fnref24"><sup>24</sup></a> Por ejemplo, el paquete <code>Biodem</code> dispone de la función <code>mtx.exp</code>, y el paquete <code>expm</code> dispone de la operación <code>%^%</code>. No obstante, hay que tener en cuenta que estas funciones no calculan las potencias de manera exacta, sino que emplean algoritmos de cálculo numérico para aproximarlas a cambio de calcularlas rápido, y por lo tanto no siempre dan el resultado exacto.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">3</span>), <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
<span class="co"># Instalamos y cargamos el paquete &quot;Biodem&quot;</span>
<span class="co"># ...</span>
<span class="kw">library</span>(Biodem)
<span class="kw">mtx.exp</span>(A, <span class="dv">20</span>) <span class="co">#A^20</span></code></pre></div>
<pre><code>##             [,1]         [,2]
## [1,] 58063278153 158631825968
## [2,] 79315912984 216695104121</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Instalamos y cargamos el paquete &quot;expm&quot;</span>
<span class="co">#...</span>
<span class="kw">library</span>(expm)
A<span class="op">%^%</span><span class="dv">20</span> <span class="co">#A^20</span></code></pre></div>
<pre><code>##             [,1]         [,2]
## [1,] 58063278153 158631825968
## [2,] 79315912984 216695104121</code></pre>
<p>El determinante de una matriz cuadrada se calcula con la función <code>det</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Y=<span class="kw">rbind</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">2</span>),<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">5</span>),<span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">2</span>))
Y</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    3    2
## [2,]    2    3    5
## [3,]   -1    3    2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">det</span>(Y)</code></pre></div>
<pre><code>## [1] -18</code></pre>
<p>Para ganar en rapidez, <code>R</code> calcula los determinantes usando un método numérico que a veces produce efectos no deseados como el siguiente:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">10</span>,<span class="dv">30</span>,<span class="dv">100</span>), <span class="dt">nrow=</span><span class="dv">2</span>)
A</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    3   30
## [2,]   10  100</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">det</span>(A)</code></pre></div>
<pre><code>## [1] 3.552714e-14</code></pre>
<p>Pero, de hecho, <span class="math display">\[
\left|\begin{array}{cc}
3 &amp; 30\\ 10 &amp;100
\end{array}\right|=
3\cdot 100-30\cdot 10=0.
\]</span></p>
<p>Por lo tanto, este determinante <span class="math inline">\(3.552714\cdot 10^{-14}\)</span> es en realidad <span class="math inline">\(0\)</span>.</p>
<p>El rango de una matriz <span class="math inline">\(A\)</span> se puede calcular mediante la instrucción <code>qr(A)\$rank</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="op">-</span><span class="dv">7</span>,<span class="dv">3</span>,<span class="op">-</span><span class="dv">1</span>,<span class="dv">16</span>,<span class="op">-</span><span class="dv">3</span>,<span class="dv">4</span>), <span class="dt">nrow=</span><span class="dv">3</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
X</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    0    1    0
## [2,]   -7    3   -1
## [3,]   16   -3    4</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">det</span>(X)</code></pre></div>
<pre><code>## [1] 12</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qr</span>(X)<span class="op">$</span>rank</code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Y=<span class="kw">rbind</span>(<span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">3</span>),<span class="kw">rep</span>(<span class="dv">1</span>,<span class="dv">3</span>))
Y</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    0    0    0
## [2,]    1    1    1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qr</span>(Y)<span class="op">$</span>rank</code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>Podemos calcular la inversa de una matriz invertible con la instrucción <code>solve</code>. Por ejemplo, para calcular la inversa <span class="math inline">\(A^{-1}\)</span> de la matriz</p>
<p><span class="math display">\[
A=\left(\begin{array}{ccc}
1 &amp; 3 &amp; 4 \\ 0 &amp; 2 &amp; -1 \\ 2 &amp; 1 &amp; 2\end{array}
\right)
\]</span> podemos entrar lo siguiente:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">0</span>,<span class="dv">2</span>,<span class="op">-</span><span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">2</span>), <span class="dt">nrow=</span><span class="dv">3</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
<span class="kw">solve</span>(A) </code></pre></div>
<pre><code>##            [,1]       [,2]        [,3]
## [1,] -0.2941176  0.1176471  0.64705882
## [2,]  0.1176471  0.3529412 -0.05882353
## [3,]  0.2352941 -0.2941176 -0.11764706</code></pre>
<p>Obtenemos</p>
<p><span class="math display">\[
A^{-1}=\left(\begin{array}{ccc}
-0.2941176 &amp; 0.1176471 &amp; 0.64705882\\
0.1176471 &amp; 0.3529412 &amp; -0.05882353\\
0.2352941 &amp; -0.2941176 &amp; -0.11764706
\end{array}
\right).
\]</span> Comprobemos si esta matriz es realmente la inversa de <span class="math inline">\(A\)</span>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A<span class="op">%*%</span><span class="kw">solve</span>(A) </code></pre></div>
<pre><code>##              [,1] [,2]          [,3]
## [1,] 1.000000e+00    0  0.000000e+00
## [2,] 5.551115e-17    1 -2.775558e-17
## [3,] 0.000000e+00    0  1.000000e+00</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">solve</span>(A)<span class="op">%*%</span>A </code></pre></div>
<pre><code>##      [,1]         [,2]         [,3]
## [1,]    1 0.000000e+00 0.000000e+00
## [2,]    0 1.000000e+00 1.110223e-16
## [3,]    0 2.775558e-17 1.000000e+00</code></pre>
<p>Los productos<code>A%*%solve(A)</code> y <code>solve(A)%*%A</code> no han dado exactamente la matriz identidad, como deberían, pero la diferencia está en la decimosexta cifra decimal. Recordad que <code>R</code> no trabaja con precisión infinita, a veces los errores de redondeo son inevitables.</p>
<p>La función <code>solve</code> también sirve para resolver sistemas de ecuaciones lineales</p>
<p><span class="math display">\[
\left.\begin{array}{c}
a_{1,1} x_1+\cdots +a_{1,n}x_n = b_1 \\
a_{2,1} x_1+\cdots +a_{2,n}x_n = b_2 \\
\vdots\qquad\ \\
a_{n,1} x_1+\cdots +a_{n,n}x_n = b_n
\end{array}
\right\}
\]</span> cuya <code>matriz del sistema</code></p>
<p><span class="math display">\[
A=\left(\begin{array}{ccc}
a_{1,1} &amp; \cdots &amp; a_{1,n} \\
\vdots &amp; \ddots &amp; \vdots\\
a_{n,1} &amp; \cdots &amp; a_{n,n}
\end{array}
\right)
\]</span></p>
<p>sea cuadrada e invertible. Para ello, se usaría la instrucción</p>
<p><code>solve(A, b)</code>,</p>
<p>donde <code>A</code> es la matriz <span class="math inline">\(A\)</span> del sistema y <code>b</code> es el vector de términos independientes</p>
<p><span class="math display">\[
b=(b_1, \ldots, b_{n}).
\]</span></p>
<p>Por ejemplo, para resolver el sistema <span class="math display">\[
\left.\begin{array}{r}
x+6y-3z = 7 \\
2x-y+z = 2\\
x+y-z = 3
\end{array}
\right\},
\]</span> que escrito en forma matricial es <span class="math display">\[
\left(\begin{array}{ccc}
1 &amp; 6 &amp; -3 \\ 2 &amp; -1 &amp; 1 \\ 1 &amp; 1 &amp; -1\end{array}
\right)\cdot 
\left(\begin{array}{c} x \\ y \\ z \end{array}
\right)=
\left(\begin{array}{c} 7 \\ 2 \\ 3 \end{array}
\right), 
\]</span> podemos entrar</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">6</span>,<span class="op">-</span><span class="dv">3</span>,<span class="dv">2</span>,<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="op">-</span><span class="dv">1</span>), <span class="dt">nrow=</span><span class="dv">3</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
A</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    6   -3
## [2,]    2   -1    1
## [3,]    1    1   -1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">b=<span class="kw">c</span>(<span class="dv">7</span>,<span class="dv">2</span>,<span class="dv">3</span>)
<span class="kw">solve</span>(A, b)</code></pre></div>
<pre><code>## [1]  1.6666667  0.4444444 -0.8888889</code></pre>
<p>y obtenemos que la solución del sistema (redondeada a 7 cifras decimales) es</p>
<p><span class="math display">\[
x=1.6666667, \ y=0.4444444, \ z=-0.8888889.
\]</span></p>
</div>
<div id="valores-y-vectores-propios-opcional" class="section level2">
<h2><span class="header-section-number">5.5</span> Valores y vectores propios (opcional)</h2>
<p>La función básica para calcular valores y vectores propios<a href="#fn25" class="footnoteRef" id="fnref25"><sup>25</sup></a> es <code>eigen</code> (en inglés, los valores y vectores propios se llaman <code>eigenvalues</code> y <code>eigenvectors</code> , respectivamente). Supongamos, por ejemplo, que queremos calcular los valores propios de la matriz</p>
<p><span class="math display">\[
A=\left(\begin{array}{ccc}2 &amp; 6 &amp; -8 \\ 0 &amp; 6 &amp; -3 \\ 0 &amp; 2 &amp; 1\end{array}
\right).
\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">6</span>,<span class="op">-</span><span class="dv">8</span>,<span class="dv">0</span>,<span class="dv">6</span>,<span class="op">-</span><span class="dv">3</span>,<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">1</span>), <span class="dt">nrow=</span><span class="dv">3</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
A</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    2    6   -8
## [2,]    0    6   -3
## [3,]    0    2    1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">eigen</span>(A)</code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 4 3 2
## 
## $vectors
##           [,1]       [,2] [,3]
## [1,] 0.2672612 -0.8164966    1
## [2,] 0.8017837  0.4082483    0
## [3,] 0.5345225  0.4082483    0</code></pre>
<p>El resultado de <code>eigen</code> es una <code>list</code> con dos objetos: <code>values</code> y <code>vectors</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(<span class="kw">eigen</span>(A))</code></pre></div>
<pre><code>## List of 2
##  $ values : num [1:3] 4 3 2
##  $ vectors: num [1:3, 1:3] 0.267 0.802 0.535 -0.816 0.408 ...
##  - attr(*, &quot;class&quot;)= chr &quot;eigen&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">eigen</span>(A)<span class="op">$</span>values</code></pre></div>
<pre><code>## [1] 4 3 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">eigen</span>(A)<span class="op">$</span>vectors</code></pre></div>
<pre><code>##           [,1]       [,2] [,3]
## [1,] 0.2672612 -0.8164966    1
## [2,] 0.8017837  0.4082483    0
## [3,] 0.5345225  0.4082483    0</code></pre>
<p>El objeto <code>values</code> es un vector con los valores propios, y el objeto <code>vectors</code> es una matriz cuyas columnas son vectores propios: la primera columna es un vector propio del primer valor propio del vector <code>values</code>, la segunda lo es del segundo, y así sucesivamente. De este modo, del resultado anterior deducimos que los valores propios de <span class="math inline">\(A\)</span> son 2, 3 y 4 y que</p>
<p><span class="math display">\[
\left(\begin{array}{c} 1 \\ 0 \\ 0\end{array}\right),
\left(\begin{array}{c} -0.8164966 \\ 0.4082483 \\ 0.4082483\end{array}\right),
\left(\begin{array}{c} 0.2672612 \\ 0.8017837 \\ 0.5345225\end{array}\right)
\]</span></p>
<p>son vectores propios de <span class="math inline">\(A\)</span> de valores propios 2, 3 y 4, respectivamente (o, para ser precisos, los dos últimos son vectores propios de valor propio 3 y 4 redondeados a 7 cifras decimales).</p>
<p>Es importante tener en cuenta algunas propiedades de la función <code>eigen</code>:</p>
<ul>
<li><p>Da los valores propios en orden decreciente de su valor absoluto (o de su módulo, si hay valores propios complejos) y repetidos tantas veces como su multiplicidad.</p></li>
<li><p>Si hay algún valor propio con multiplicidad mayor que 1, da tantos vectores de este valor propio como su multiplicidad. Además, en este caso procura que estos vectores propios sean linealmente independientes. Por lo tanto, cuando da vectores propios repetidos de algún valor propio es porque para este valor propio no existen tantos vectores propios linealmente independientes como su multiplicidad y, por consiguiente, la matriz no es diagonalizable.</p></li>
</ul>
<p>Del resultado de <code>eigen(A)</code> se puede obtener una descomposición canónica <span class="math display">\[
A= P\cdot D\cdot P^{-1}
\]</span> de una matriz diagonalizable <span class="math inline">\(A\)</span>: basta tomar como <span class="math inline">\(D\)</span> la matriz diagonal que tiene como diagonal principal el vector <code>eigen(A)$values</code> y como <span class="math inline">\(P\)</span> la matriz <code>eigen(A)$vectors</code>.</p>
<p>Para construir una matriz diagonal cuya diagonal principal sea un <code>vector</code> dado, podemos usar la instrucción <code>diag(``vector</code> <code>)</code>. Si aplicamos <code>diag</code> a un número <span class="math inline">\(n\)</span>, produce la matriz identidad de orden <span class="math inline">\(n\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">diag</span>(<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="op">-</span><span class="dv">1</span>))</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    2    0    0
## [2,]    0    5    0
## [3,]    0    0   -1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">diag</span>(<span class="dv">3</span>)</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    0    0
## [2,]    0    1    0
## [3,]    0    0    1</code></pre>
<p>La función <code>diag</code> ya había salido en la Sección <a href="#sec:entrmatr"><strong>??</strong></a>: si se aplica a una matriz, se obtiene el vector formado por sus entradas <span class="math inline">\((1,1), (2,2),\ldots\)</span>; ahora vemos que si se aplica a un vector, produce una matriz diagonal.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">B=<span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
B</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5]
## [1,]    1    2    3    4    5
## [2,]    6    7    8    9   10</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">diag</span>(B)</code></pre></div>
<pre><code>## [1] 1 7</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">diag</span>(<span class="kw">diag</span>(B))</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    0
## [2,]    0    7</code></pre>
<p>Veamos un ejemplo de uso de <code>eigen</code> para calcular una descomposición canónica. Como hemos visto, la matriz <span class="math display">\[
A=\left(\begin{array}{ccc}2 &amp; 6 &amp; -8 \\ 0 &amp; 6 &amp; -3 \\ 0 &amp; 2 &amp; 1\end{array}
\right)
\]</span> es de orden 3 y tiene sus tres valores propios diferentes. Por lo tanto, es diagonalizable y las matrices de una descomposición canónica serían las siguientes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">D=<span class="kw">diag</span>(<span class="kw">eigen</span>(A)<span class="op">$</span>values) <span class="co">#Matriz diagonal D de valores propios</span>
D</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    4    0    0
## [2,]    0    3    0
## [3,]    0    0    2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">P=<span class="kw">eigen</span>(A)<span class="op">$</span>vectors <span class="co">#Matriz P de vectores propios</span>
P</code></pre></div>
<pre><code>##           [,1]       [,2] [,3]
## [1,] 0.2672612 -0.8164966    1
## [2,] 0.8017837  0.4082483    0
## [3,] 0.5345225  0.4082483    0</code></pre>
<p>Comprobemos que, efectivamente, <span class="math inline">\(A=P\cdot D\cdot P^{-1}\)</span>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">P<span class="op">%*%</span>D<span class="op">%*%</span><span class="kw">solve</span>(P)</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    2    6   -8
## [2,]    0    6   -3
## [3,]    0    2    1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    2    6   -8
## [2,]    0    6   -3
## [3,]    0    2    1</code></pre>
<p>Por consiguiente, una descomposición canónica de <span class="math inline">\(A\)</span> es (salvo redondeos)</p>
<p><span class="math display">\[
A=\left(\begin{array}{ccc}
0.2672612 &amp; -0.8164966 &amp; 1\\
0.8017837 &amp; 0.4082483 &amp; 0\\
0.5345225 &amp; 0.4082483 &amp; 0
\end{array}
\right)\!\cdot\!
\left(\begin{array}{ccc}
4 &amp; 0 &amp; 0 \\ 0 &amp; 3 &amp; 0\\ 0 &amp; 0 &amp; 2 \end{array}
\right)\!\cdot\!
\left(\begin{array}{ccc}
0.2672612 &amp; -0.8164966 &amp; 1\\
0.8017837 &amp; 0.4082483 &amp; 0\\
0.5345225 &amp; 0.4082483 &amp; 0
\end{array}
\right)^{-1}.
\]</span></p>
<p>Veamos otro ejemplo. Queremos decidir si la matriz <span class="math display">\[
B=\left(\begin{array}{ccc}0 &amp; 1 &amp; 0 \\ -7 &amp; 3 &amp; -1 \\ 16 &amp; -3 &amp; 4\end{array}
\right)
\]</span> es diagonalizable y, en caso afirmativo, obtener una descomposición canónica.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">B=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="op">-</span><span class="dv">7</span>,<span class="dv">3</span>,<span class="op">-</span><span class="dv">1</span>,<span class="dv">16</span>,<span class="op">-</span><span class="dv">3</span>,<span class="dv">4</span>), <span class="dt">nrow=</span><span class="dv">3</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
<span class="kw">eigen</span>(B)</code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 3 2 2
## 
## $vectors
##            [,1]       [,2]       [,3]
## [1,] -0.1301889 -0.1825742 -0.1825742
## [2,] -0.3905667 -0.3651484 -0.3651484
## [3,]  0.9113224  0.9128709  0.9128709</code></pre>
<p>Da dos veces el mismo vector propio de valor propio 2. Esto significa que <span class="math inline">\(B\)</span> no tiene dos vectores propios linealmente independientes de este valor propio, y, por lo tanto, no es diagonalizable.</p>
</div>
<div id="matrices-complejas-opcional" class="section level2">
<h2><span class="header-section-number">5.6</span> Matrices complejas (opcional)</h2>
<p>La mayoría de las instrucciones explicadas en esta lección para operar con matrices numéricas sirven sin ningún cambio para operar con matrices de entradas números complejos. Por ejemplo, para elevar al cuadrado la matriz <span class="math display">\[
\left( \begin{array}{cc} 3-2i &amp; 5+3\\ 1+2i &amp; 2-i \end{array}
\right),
\]</span> podemos entrar:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">3</span><span class="op">-</span>2i,<span class="dv">5</span><span class="op">+</span>3i,<span class="dv">1</span><span class="op">+</span>2i,<span class="dv">2</span><span class="op">-</span>1i), <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
A</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,] 3-2i 5+3i
## [2,] 1+2i 2-1i</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A<span class="op">%*%</span>A</code></pre></div>
<pre><code>##       [,1]  [,2]
## [1,]  4+1i 34+0i
## [2,] 11+7i  2+9i</code></pre>
<p>Para calcular sus valores y vectores propios, podemos entrar:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">eigen</span>(A)</code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 4.902076+1.101916i 0.097924-4.101916i
## 
## $vectors
##                     [,1]                 [,2]
## [1,] 0.8483705+0.000000i  0.8519823+0.000000i
## [2,] 0.4695014+0.244614i -0.5216168-0.045189i</code></pre>
<p>Y para resolver el sistema de ecuaciones <span class="math display">\[
\left.
\begin{array}{rl} 
(3-2i)x+(5+3i)y &amp; = 2-i\\
(1+2i)x+(2-i)y &amp; = 3 
\end{array}
\right\}
\]</span> podemos entrar:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">3</span><span class="op">-</span>2i,<span class="dv">5</span><span class="op">+</span>3i,<span class="dv">1</span><span class="op">+</span>2i,<span class="dv">2</span><span class="op">-</span>1i), <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
b=<span class="kw">c</span>(<span class="dv">2</span><span class="op">-</span>1i,<span class="dv">3</span>)
<span class="kw">solve</span>(A, b)</code></pre></div>
<pre><code>## [1] 0.4705882-0.7176471i 0.4823529+0.1294118i</code></pre>
<p>La excepción más importante son los determinantes.</p>
<pre><code>&gt; det(A)
Error in determinant.matrix(x, logarithm = TRUE, ...) : 
  &#39;determinant&#39; not currently defined for complex matrices</code></pre>
<p>Pero resulta que el determinante de una matriz es igual al producto de sus valores propios, incluyendo repeticiones. Por lo tanto, para calcular el determinante de una matriz compleja <span class="math inline">\(A\)</span> podemos usar <code>prod(eigen(A)$values)</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">A=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">3</span><span class="op">-</span>2i, <span class="dv">5</span><span class="op">+</span>3i, <span class="dv">1</span><span class="op">+</span>2i, <span class="dv">2</span><span class="op">-</span>1i), <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
<span class="kw">prod</span>(<span class="kw">eigen</span>(A)<span class="op">$</span>values)</code></pre></div>
<pre><code>## [1] 5-20i</code></pre>
</div>
<div id="guia-rapida-de-funciones-1" class="section level2">
<h2><span class="header-section-number">5.7</span> Guía rápida de funciones</h2>
<ul>
<li><code>matrix</code> sirve para construir una matriz a partir de un vector. Algunos parámetros importantes:</li>
<li><code>byrow</code>: un parámetro lógico para indicar si la matriz se construye por filas (igualado a <code>TRUE</code>) o por columnas (valor por defecto).</li>
<li><code>nrow</code>: el número de filas.</li>
<li><code>ncol</code>: el número de columnas.</li>
<li><code>cbind</code> concatena vectores y matrices por columnas.</li>
<li><code>rbind</code> concatena vectores y matrices por filas.</li>
<li><code>dimnames</code> permite poner nombres a las filas y las columnas de una matriz.</li>
<li><code>matriz</code> <code>[..., ...]</code> se usa para especificar un elemento, una fila, una columna o una submatriz de la <code>matriz</code>. Si extraemos una fila o una columna con el parámetro <code>drop=FALSE</code>, el resultado es una matriz y no un vector.</li>
<li><code>diag</code> tiene dos significados: aplicada a un vector, construye una matriz diagonal, y aplicada a una matriz, extrae su diagonal principal.</li>
<li><code>nrow</code> da el número de filas de una matriz.</li>
<li><code>ncol</code> da el número de columnas de una matriz.</li>
<li><code>dim</code> da un vector con las dimensiones de una matriz.</li>
<li><code>sum</code>, <code>prod</code> y <code>mean</code> calculan, respectivamente, la suma, el producto y la media de las entradas de una matriz.</li>
<li><code>colSums</code> y <code>rowSums</code> calculan, respectivamente, las sumas de las entradas de cada una de las columnas y de cada una de las filas de una matriz.</li>
<li><code>colMeans</code> y <code>rowMeans</code> calculan, respectivamente, las medias de cada una de las columnas y de cada una de las filas de una matriz.</li>
<li><code>apply(``matriz</code> <code>, MARGIN=\ldots, FUN=``función</code> <code>)</code> aplica la <code>función</code> a las filas (<code>MARGIN=1</code>), a las columnas (<code>MARGIN=2</code>) o a todas las entradas (<code>MARGIN=c(1, 2)</code>) de la <code>matriz</code> .</li>
<li>Signos de operaciones con matrices:</li>
</ul>
<table>
<thead>
<tr class="header">
<th>Función</th>
<th>Suma</th>
<th>Producto por escalar</th>
<th>Producto</th>
<th>Producto Potencia (paquete <code>expm</code>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Signo</strong></td>
<td><code>*</code></td>
<td><code>*</code></td>
<td><code>%*%</code></td>
<td><code>%^%</code></td>
</tr>
</tbody>
</table>
<!--
\begin{center}
\begin{tabular}{|c|c|c|c|c|}
\hline
\multirow{2}{*}{\begin{minipage}{0.15\textwidth}\begin{center} Función \end{center} \end{minipage}}  &  \multirow{2}{*}{\begin{minipage}{0.15\textwidth}\begin{center} Suma \end{center} \end{minipage}}  &  \multirow{2}{*}{\begin{minipage}{0.15\textwidth}\begin{center} Producto por escalar \end{center} \end{minipage}}  & \multirow{2}{*}{\begin{minipage}{0.15\textwidth}\begin{center} Producto \end{center} \end{minipage}} & \multirow{2}{*}{\begin{minipage}{0.18\textwidth}\begin{center} Potencia (paquete `expm`) \end{center} \end{minipage}} \\[0.5cm] \hline
Signo & `+`\vphantom{$\Big($}& `*`& \verb?%*%? & \verb?%^%? 
\\ \hline
\end{tabular}
\end{center}
-->
<ul>
<li><code>t</code> calcula la traspuesta de una matriz.</li>
<li><code>det</code> calcula el determinante de una matriz.</li>
<li><code>qr(``matriz</code> <code>)\$rank</code> calcula el rango de la <code>matriz</code> .</li>
<li><code>solve</code>, aplicada a una matriz invertible <span class="math inline">\(A\)</span>, calcula su inversa <span class="math inline">\(A^{-1}\)</span>, y aplicada a una matriz invertible <span class="math inline">\(A\)</span> y un vector <span class="math inline">\(b\)</span>, calcula <span class="math inline">\(A^{-1}\cdot b\)</span>.</li>
<li><code>eigen</code> calcula los valores y vectores propios de una matriz. El resultado es una <code>list</code> con dos componentes:</li>
<li><code>values</code>: un vector con los valores propios.</li>
<li><code>vectors</code>: una matriz cuyas columnas son vectores propios de los correspondientes valores propios.</li>
</ul>
</div>
<div id="ejercicio-opcional" class="section level2">
<h2><span class="header-section-number">5.8</span> Ejercicio (opcional)</h2>
<p>Sean <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span> dos cantidades de las cuales efectuamos una serie de <span class="math inline">\(k\)</span> observaciones conjuntas, de forma que obtenemos una secuencia de pares de valores <span class="math display">\[
(x_{1}, y_{1}), (x_{2}, y_{2}), \ldots, (x_{k}, y_{k}).
\]</span> Como veíamos en la Lección <a href="chap-lm.html#chap:lm">3</a>, si queremos encontrar la recta <span class="math inline">\(y=ax+b\)</span> que aproxime mejor estas observaciones, una posibilidad es calcular los valores <span class="math inline">\(a, b\in \mathbb{R}\)</span> tales que <span class="math display">\[
\sum_{i=1}^k (ax_{i}+b-y_{i})^2
\]</span> sea mínimo. De este modo encontraríamos la <code>recta de regresión por mínimos cuadrados</code> . Resulta (no lo demostraremos aquí) que los coeficientes <span class="math inline">\(a\)</span> y <span class="math inline">\(b\)</span> de esta recta de regresión se obtienen por medio de la fórmula <span class="math display">\[
\left(\begin{matrix} b\\ a \end{matrix}
\right)=
(D_{2}\cdot D_{2}^t)^{-1}\cdot D_{2}\cdot w, 
\]</span> donde <span class="math display">\[
w=\left(\begin{matrix}y_{1}\\ \vdots\\ y_{k}\end{matrix}
\right), \quad
D_{2}=\left(\begin{matrix}
1 &amp; 1 &amp; \ldots &amp; 1 \\
x_{1} &amp; x_{2} &amp; \ldots &amp; x_{k}
\end{matrix}
\right).
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li>Calculad de este modo los valores de <span class="math inline">\(a\)</span> y <span class="math inline">\(b\)</span> cuando las observaciones son las de la Tabla <a href="chap-matrix.html#tab:Ex501">5.1</a> (es la Tabla <a href="#tab:1"><strong>??</strong></a> de la Lección <a href="chap-lm.html#chap:lm">3</a>), y comprobad que obtenéis el mismo resultado que obteníamos en su momento con la función <code>lm</code>.</li>
</ol>
<table>
<caption><span id="tab:Ex501">Tabla 5.1: </span>Alturas medias de niños por edad.</caption>
<tbody>
<tr class="odd">
<td align="left">x: (edad, en años)</td>
<td align="right">1.00</td>
<td align="right">2.00</td>
<td align="right">3.00</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="right">9.00</td>
<td align="right">11.00</td>
<td align="right">13.00</td>
</tr>
<tr class="even">
<td align="left">y: (altura, en cm)</td>
<td align="right">76.11</td>
<td align="right">86.45</td>
<td align="right">95.27</td>
<td align="right">109.18</td>
<td align="right">122.03</td>
<td align="right">133.73</td>
<td align="right">143.73</td>
<td align="right">156.41</td>
</tr>
</tbody>
</table>
<!--
\begin{table}[htb]
\abovecaptionskip=-3pt
\begin{center}
\begin{tabular}{ccccccccc}
\toprule
$x$: (edad, en años) & 1 & 2 & 3 & 5 & 7 & 9 & 11 & 13\\
\midrule
$y$: (altura, en cm) & 76.11 & 86.45 & 95.27 & 109.18 & 122.03 & 133.73 & 143.73 & 156.41\\
\bottomrule
\end{tabular}
\end{center}
\caption{Alturas medias de niños por edad.\label{tab:Ex5.1}} 
\end{table}
-->
<p>De manera similar, si queremos obtener una función cuadrática <span class="math inline">\(y=a x^2+b x+c\)</span> que aproxime los pares <span class="math inline">\((x_i, y_i)_{y=1, \ldots, k}\)</span>, podemos buscar los coeficientes <span class="math inline">\(a, b, c\)</span> que minimicen el valor de <span class="math display">\[
\sum_{i=1}^k (ax_{i}^2+bx_{i}+c-y_{i})^2.
\]</span> Estos coeficientes se obtienen de manera similar, por medio de la fórmula <span class="math display">\[
\left(\begin{matrix}
c\\ b\\ a \end{matrix}
\right)=
(D_{3}\cdot D_{3}^t)^{-1}\cdot D_{3}\cdot w, 
\]</span> donde <span class="math inline">\(w\)</span> es como antes y ahora <span class="math display">\[
D_{3}=\left(\begin{matrix}
1 &amp; 1 &amp; \ldots &amp; 1 \\
x_{1} &amp; x_{2} &amp; \ldots &amp; x_{k}\\[0.5ex]
x_{1}^2 &amp; x_{2}^2 &amp; \ldots &amp; x_{k}^2
\end{matrix}
\right).
\]</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li><p>Calculad los valores de <span class="math inline">\(a, b, c\)</span> para los pares <span class="math inline">\((x,y)\)</span> de la Tabla @ref(tab:Ex5.1).</p></li>
<li><p>Con <code>R</code>, podemos calcular estos coeficientes de la manera siguiente: si definimos un nuevo vector <span class="math inline">\(z\)</span> con los cuadrados de los valores de <span class="math inline">\(x\)</span>, y aplicamos la función</p>
<pre><code>lm(y~x+z)</code></pre>
<p>obtenemos los coeficientes de la función lineal <span class="math inline">\(y=c+bx+az\)</span> que mejor se ajusta a las ternas <span class="math inline">\((x_i,z_i,y_i)\)</span>, en el sentido de que minimiza la suma de las diferencias al cuadrado entre los valores <span class="math inline">\(y_i\)</span> y los correspondientes <span class="math inline">\(c+bx_i+az_i\)</span>; substituyendo entonces <span class="math inline">\(z\)</span> por <span class="math inline">\(x^2\)</span> en esta relación, obtenemos la función <span class="math inline">\(y=c+bx+ax^2\)</span> que buscábamos. Comprobad que, efectivamente, coincide con la calculada en el apartado anterior.</p></li>
</ol>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="23">
<li id="fn23"><p>Si necesitáis repasar los conceptos básicos sobre operaciones de matrices que aparecen en esta sección, podéis consultar la entrada sobre matrices en la <em>Wikipedia</em>, <a href="http://es.wikipedia.org/wiki/Matriz_(matemáticas)" class="uri">http://es.wikipedia.org/wiki/Matriz_(matemáticas)</a> .<a href="chap-matrix.html#fnref23">↩</a></p></li>
<li id="fn24"><p>Explicamos el manejo de paquetes en la Sección <a href="chap-0.html#sec:paquetes">1.5</a><a href="chap-matrix.html#fnref24">↩</a></p></li>
<li id="fn25"><p>Si necesitáis repasar las definiciones de vector y valor propio de una matriz y de descomposición canónica de una matriz diagonalizable, y por qué son importantes, podéis consultar las entradas correspondientes de la <em>Wikipedia</em>: <a href="http://es.wikipedia.org/wiki/Vector_propio_y_valor_propio" class="uri">http://es.wikipedia.org/wiki/Vector_propio_y_valor_propio</a> y <a href="http://es.wikipedia.org/wiki/Matriz_diagonalizable" class="uri">http://es.wikipedia.org/wiki/Matriz_diagonalizable</a> .<a href="chap-matrix.html#fnref25">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap-vect.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-df.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/RicUIB/AprendeR2.1/edit/master/05chap04_Matrices.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["AprendeR-Parte-I.pdf", "AprendeR-Parte-I.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
